[package]
name = "physim"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
crossbeam = "0.8.4"
ctrlc = "3.4.7"
glium = { git = "https://github.com/glium/glium", branch = "master" }
